### ISSUE TITLE
Changes to RCL project's content requires referencing web app to be re-build for it take get latest RCL project's Views dll

### ISSUE THREAD

**Issue by kichalla** [aspnet/Razor#2301] opened 2018-04-24 20:04 UTC
**Repro Steps:**

- Create a new Razor Class Library (RCL) project | Build it
- Add a new Razor Pages(RP) web application | Reference the above created RCL project | Build it
- Ctrl + F5 | access http://localhost:port/myfeature/page1 | you should be able to see an empty page with Page1 title
- Now add some content tto the body of RCL project's `Page1.cshtml` | Save it | Ctrl + F5 | access http://localhost:port/myfeature/page1

**Expected**: Updated changes to the html body are reflected
**Actual**: Updated changes do not show up as the updated Views dll is not copied to the RP project's output

**Workaround**: Rebuild RP project | Ctrl + F5

**Comment by mkArtakMSFT** [comment] 2018-04-24 20:58
Potential dupe of https://github.com/aspnet/Razor/issues/2300

**Comment by mkArtakMSFT** [comment] 2018-05-01 05:05
@pranavkm, do we have more info regarding whether this is a dupe or not?

**Comment by pranavkm** [comment] 2018-05-01 13:34
I closed the other one as dup.

**Comment by mkArtakMSFT** [comment] 2018-05-01 19:46
@pranavkm, can you please link the PR to this issue?

**Comment by pranavkm** [comment] 2018-05-01 21:01
https://github.com/aspnet/Razor/pull/2316

**Comment by pranavkm** [comment] 2018-05-01 23:55
Fixed in 05c84f008a5a6536b6ce84c3dbf8c468dc08f4c0

**Closed by pranavkm** 2018-05-01 23:55 UTC
Labels: 3 - Done, SHP: Approved, bug
