### ISSUE TITLE
Razor confusing code and html intellisense

### ISSUE THREAD

**Issue by boomtopper** [aspnet/Razor#1157] opened 2017-04-03 10:08 UTC
Hi,

I'm using Visual Studio 2017 with an ASP.NET project created with VB.NET.  I'm finding that intellisense is getting confused, if I start a statement with the '@html.' intellisense shows the wrong helpers and thinks that this is HTML. If I backspace the '.' then readd it, it then shows the correct helpers. I've attached a gif to demonstrate what is happening.

![razorbug](https://cloud.githubusercontent.com/assets/264872/24604687/bdddaf9c-185d-11e7-9469-98430285eeed.gif)

**Comment by NTaylorMullen** [comment] 2017-04-03 17:02
@boomtopper what project template are you using?

**Comment by boomtopper** [comment] 2017-04-03 17:41
I'm using a standard ASP.NET MVC VB.NET Dotnet Framework 4.5 template. Is that what you meant?

**Comment by boomtopper** [comment] 2017-04-04 07:01
I've gone and tested this by creating a completely new ASP.NET MVC Web Application and added a partial view and did the above and it did the same thing and it does the same behavior.  One thing I noticed about it is if I press tab to complete when typing 'html' it will give me the correct helpers but if I enter the '.' after html it gives the wrong list.

I have also gone and tested this with a new C# project but it works as expected, so it looks like it's to do with it being VB.NET.

**Comment by boomtopper** [comment] 2017-04-11 08:48
Have posted this on the visual studio developer community
https://developercommunity.visualstudio.com/content/problem/41275/razor-intellisense-showing-wrong-helpers.html

**Comment by Eilon** [comment] 2017-04-12 02:23
Hi @boomtopper thank you for reporting this issue in Razor. We have confirmed that this is a valid bug.

We evaluated the cost of producing and shipping a fix and because it is very high, we are closing this issue as "won't fix". The usage of vbhtml is very low and the fix for this does not meet the bar for the next release.

The workaround for the issue is what is noted in the original recording you sent: press <kbd>Backspace</kbd> and then press <kbd>.</kbd> again to activate the Intellisense menu.

**Closed by Eilon** 2017-04-12 02:23 UTC
