### ISSUE TITLE
Test failure: Publish_WithP2P_WorksWhenBuildProjectReferencesIsDisabled

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Razor#2548] opened 2018-08-19 13:00 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=535151&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
Microsoft.AspNetCore.Razor.Design.IntegrationTests.Assert+BuildFailedException : Build failed.
dotnet msbuild /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppVersion=2.2.0-preview1-26618-02 /p:NETStandardLibraryPackageVersion=2.0.3 /restore /p:_RazorBuildServerPipeName="acf072b6-7901-447a-900d-2b4b9daf26d4" /p:Configuration=Release 
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restoring packages for C:\b\t\buildTmp\Razor\22ciet4t.4n4\ClassLibrary\ClassLibrary.csproj...
  Restoring packages for C:\b\t\buildTmp\Razor\22ciet4t.4n4\AppWithP2PReference\AppWithP2PReference.csproj...
  Restoring packages for C:\b\t\buildTmp\Razor\22ciet4t.4n4\ClassLibrary2\ClassLibrary2.csproj...
  Generating MSBuild file C:\b\t\buildTmp\Razor\22ciet4t.4n4\AppWithP2PReference\obj\AppWithP2PReference.csproj.nuget.g.props.
  Generating MSBuild file C:\b\t\buildTmp\Razor\22ciet4t.4n4\ClassLibrary\obj\ClassLibrary.csproj.nuget.g.props.
  Generating MSBuild file C:\b\t\buildTmp\Razor\22ciet4t.4n4\ClassLibrary\obj\ClassLibrary.csproj.nuget.g.targets.
  Generating MSBuild file C:\b\t\buildTmp\Razor\22ciet4t.4n4\AppWithP2PReference\obj\AppWithP2PReference.csproj.nuget.g.targets.
  Restore completed in 338.65 ms for C:\b\t\buildTmp\Razor\22ciet4t.4n4\ClassLibrary\ClassLibrary.csproj.
  Restore completed in 331.25 ms for C:\b\t\buildTmp\Razor\22ciet4t.4n4\AppWithP2PReference\AppWithP2PReference.csproj.
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.Assert.BuildPassed(MSBuildResult result) in /_/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/Assert.cs:line 27
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.PublishIntegrationTest.Publish_WithP2P_WorksWhenBuildProjectReferencesIsDisabled() in /_/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/PublishIntegrationTest.cs:line 378
--- End of stack trace from previous location where exception was thrown ---
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @mkArtakMSFT

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-19 13:00
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mkArtakMSFT** [comment] 2018-08-20 15:13
@ajaybhargavb, can you please handle this? Thanks!

**Comment by ajaybhargavb** [comment] 2018-08-27 18:36
This test looks like something failed during restore. I am unable to reproduce this plus it hasn't failed in 8 days. Moreover, this test hasn't had a failure since June. (also because of restore issues)
![image](https://user-images.githubusercontent.com/1579269/44678001-2997f280-a9ec-11e8-8c41-13dfbcbf8bfe.png)

I'm closing this for now.

**Closed by ajaybhargavb** 2018-08-27 18:36 UTC
Labels: 1 - Ready, PRI: 1 - Required, task, test-failure
