### ISSUE TITLE
Bring back ITagHelperTypeResolver equivalent

### ISSUE THREAD

**Issue by dazinator** [aspnet/Razor#1995] opened 2018-01-31 13:33 UTC
Turns out I am not the only person who used this in aspnet core 1.x and found it had gone in 2.0!

I was using a custom implementation of this to support using a glob pattern for both the assembly portion and type portion of the @addTagHelper directive.

Please can you provide a mechanism for us to automatically include a bunch of tag helpers on a razor page as per our own resoution logic.

Here is one scenario where it would be useful:

1. A developer would like any tag helper assembly dropped in a "plugins" folder to be applied to the razor page when the application next restarts.

The above used to be possible if at startup, you load plugins as assemblyparts, then have an add tag helper type resolver that was capable of resolving tag helper types given a glob pattern for the directive that worked accross assembly name not just type name.

**Comment by NTaylorMullen** [comment] 2018-01-31 19:14
@dazinator for the interim if you're looking to have auto-inclusions you can definitely make that happen (we just don't allow you to change what `@addTagHelper` means in regards to TagHelpers). We currently expose an [ITagHelperFeature](https://github.com/aspnet/Razor/blob/99010aaea45dbcc821e96c58fa9b71590069560c/src/Microsoft.AspNetCore.Razor.Language/ITagHelperFeature.cs#L8) which controls which TagHelpers are used during parsing.

If you were to replace the MVC engine (`RazorEngine`) by consuming the existing engine, extracting all of its features/phases and then adding your own you could add your own TagHelper logic. I know this isn't ideal but can serve as a stop-gap until we have a 1st class concept that enables you to configure MVCs RazorEngine without replacing the whole darn thing 😉

**Comment by dazinator** [comment] 2018-02-01 00:46
Thanks - I will look more into how I can leverage the ITagHelperTypeFeature you linked. I want to avoid deriving my own RazorEngine at all costs though because I just know it's going to be a rabbit hole.. I am already down like 5 rabbit holes. It's like the movie inception - but with rabbit holes  :-)

**Comment by mkArtakMSFT** [comment] 2018-02-02 17:31
Thank you for your feedback.
We're closing this issue as the behavior discussed seems to be by design.

**Closed by mkArtakMSFT** 2018-02-02 17:31 UTC
