### ISSUE TITLE
Razor not detect changes in files in folder using hardlink

### ISSUE THREAD

**Issue by raphaelm22** [aspnet/Razor#1391] opened 2017-05-29 20:10 UTC
I have many projects that share the same *.cshtml files, so that they are not duplicated, I used the folders with hardlink. But when these files are changed, RazorEnginer (or FileProvider) does not recognize this change. Would this be a bug in FileProvider?

Command to create Hardlink
`>mklink /d "Home"  "..\..\Common\CustomViews\Home"`

_An image to try to exemplify the situation_
![image](https://cloud.githubusercontent.com/assets/11078528/26561036/8045d550-4491-11e7-8f32-c054e1ddb563.png)

**Comment by rynowak** [comment] 2017-05-30 18:05
@pranavkm are you familiar with this?

> Would this be a bug in FileProvider?

The most likely case is that this is a bug or design limitation in file provider. I want to check if anyone around here knows the history of this.

I believe we did some work to make things like this work with some degree of fidelity in the file provider.

**Comment by raphaelm22** [comment] 2017-05-30 19:35
One point of attention, the Razor detected the change in the file when I used hardlink in the file (not in the directory as I did previously)

Command used to create Hardlink in file: 
`>mklink /h "Index.cshml" "[...]\Common\CustomViews\Home\Index.cshtml"`

_Thank you for attention!_

**Comment by pranavkm** [comment] 2017-05-31 16:13
Might be a limitation of the file system watcher where it does not follow symlinks. There is a environment variable you can set to make it additionally use disk based polling: `set DOTNET_USE_POLLING_FILE_WATCHER=1`. It was designed for Docker development scenarios which are pretty close to what you're attempting to do here. Does that help in your case?

**Comment by raphaelm22** [comment] 2017-05-31 17:06
@pranavkm worked perfectly. I can even debug the original file and the file inside the linked folder.

Thank you @pranavkm  and @rynowak

**Comment by Eilon** [comment] 2017-06-09 22:56
Closing because there are no plans to make further improvements in this area. Using polling is the recommended approach.

**Closed by Eilon** 2017-06-09 22:56 UTC
Labels: investigate
