### ISSUE TITLE
Match `@model` directive only at outermost level of file

### ISSUE THREAD

**Issue by dougbu** [aspnet/Razor#741] opened 2016-04-30 04:47 UTC
As @Rick-Anderson illustrated in [this comment](https://github.com/aspnet/Docs/pull/1138/files/a16abb1f5c7bf4d4970264dab72ee23ef8633235#r61658087), `@model` is always parsed as a Razor Directive. This is over-greedy and not particularly useful in almost all cases i.e. except at the outermost level of the Razor source file.

For example

```
@{
    var model = new MyModel();
    Layout = "";
}

<input asp-for="@model.Name"/>
```

results in the following error:

```
Unterminated string literal. Strings that start with a quotation mark (") must be terminated before the end of the line. However, strings that start with @ and a quotation mark (@") can span multiple lines.
```

The workaround is to use parentheses e.g. `<input asp-for="@(model.Name)"/>`. But that's not particularly discoverable. It's also a case where tag helpers are less usable than HTML helpers since `@Html.TextBoxFor(m => model.Name)` works just fine.

**Comment by Eilon** [comment] 2016-05-05 18:08
Hmm that's kind of annoying. I'm proactively moving to Backlog because this is not a regression (I just tried MVC 5.x and you get nearly the same error, and for exactly the same reason).

**Comment by dougbu** [comment] 2016-05-05 18:15
@Eilon Backlog isn't horrible. But note this is more important here because tag helpers. In MVC 5.x you don't _need_ `@model` in C#.

**Comment by Eilon** [comment] 2016-05-05 20:30
@dougbu the particular usage shown here is quite unusual. Come to think of it, why is a doc even showing that? You should use the provided model from your controller via `@Model`.

**Comment by Eilon** [comment] 2016-05-05 20:32
I added a comment to the doc PR stating that we shouldn't even show this.

**Comment by dougbu** [comment] 2016-05-05 21:14
Hmm, what about the `foreach (var model in Model) { ... }` case we sometimes see in user-submitted bugs?

**Comment by Eilon** [comment] 2016-05-05 21:25
That looks super weird. Certainly someone could do it. But it never worked to begin with...

**Comment by Eilon** [comment] 2017-01-09 22:59
Closing.

**Closed by Eilon** 2017-01-09 22:59 UTC
Labels: bug
