### ISSUE TITLE
Visual Studio 2015 crash: InvalidCastException

### ISSUE THREAD

**Issue by wstaelens** [aspnet/Razor#906] opened 2016-12-20 08:56 UTC
Visual Studio 2015 update 3 crash.

```
Faulting application name: devenv.exe, version: 14.0.25420.1, time stamp: 0x57685d85
Faulting module name: KERNELBASE.dll, version: 10.0.14393.479, time stamp: 0x58256d37
Exception code: 0xe0434352
Fault offset: 0x000da832
Faulting process id: 0x2d84
Faulting application start time: 0x01d25a9a00726d72
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 776117d8-5a06-466e-8744-8f4ee01dd335
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.CSharpCodeVisitor.RenderDesignTimeExpressionBlockChunk(Microsoft.AspNetCore.Razor.Chunks.ExpressionBlockChunk)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.CSharpCodeVisitor.Visit(Microsoft.AspNetCore.Razor.Chunks.ExpressionBlockChunk)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.ChunkVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Accept(Microsoft.AspNetCore.Razor.Chunks.Chunk)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.ChunkVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Accept(System.Collections.Generic.IList`1<Microsoft.AspNetCore.Razor.Chunks.Chunk>)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.CSharpCodeVisitor.Visit(Microsoft.AspNetCore.Razor.Chunks.TemplateChunk)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.ChunkVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Accept(Microsoft.AspNetCore.Razor.Chunks.Chunk)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.ChunkVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Accept(System.Collections.Generic.IList`1<Microsoft.AspNetCore.Razor.Chunks.Chunk>)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.CSharpCodeVisitor.RenderDesignTimeExpressionBlockChunk(Microsoft.AspNetCore.Razor.Chunks.ExpressionBlockChunk)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.CSharpCodeVisitor.Visit(Microsoft.AspNetCore.Razor.Chunks.ExpressionBlockChunk)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.ChunkVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Accept(Microsoft.AspNetCore.Razor.Chunks.Chunk)
   at Microsoft.AspNetCore.Razor.CodeGenerators.Visitors.ChunkVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Accept(System.Collections.Generic.IList`1<Microsoft.AspNetCore.Razor.Chunks.Chunk>)
   at Microsoft.AspNetCore.Razor.CodeGenerators.CSharpCodeGenerator.Generate()
   at Microsoft.AspNetCore.Razor.RazorTemplateEngine.GenerateCodeCore(Microsoft.AspNetCore.Razor.Text.ITextDocument, System.String, System.String, System.String, System.String, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.AspNetCore.Razor.RazorTemplateEngine.GenerateCode(Microsoft.AspNetCore.Razor.Text.ITextBuffer, System.String, System.String, System.String, System.Nullable`1<System.Threading.CancellationToken>)
   at Microsoft.AspNetCore.Razor.Editor.BackgroundParser+BackgroundThread.ParseChange(Microsoft.AspNetCore.Razor.Text.ITextBuffer, System.Threading.CancellationToken)
   at Microsoft.AspNetCore.Razor.Editor.BackgroundParser+BackgroundThread.WorkerLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

I was busy adding new code to a line and updating old code, mainly changing and playing with @{}  @() @: tags

code that i was editing (adding or removing @( or @{ tag 
```
@((version?.Version != null) ? @{ @:<td class="y"><input asp-for="@kvp.Value[i]" type="checkbox" /></td>} : @:<td class="n"><input asp-for="@kvp.Value[i]" type="checkbox" /></td>
``` 

```
.NET Command Line Tools (1.0.0-preview2-003156)

Product Information:
 Version:            1.0.0-preview2-003156
 Commit SHA-1 hash:  33dabee5d8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

Note: that tag helper intellisense or color does not work here. No idea why.

**Comment by NTaylorMullen** [comment] 2016-12-20 17:50
It might not look exactly the same but the underlying implementation looks to be. Duplicate of https://github.com/aspnet/Razor/issues/804

**Closed by NTaylorMullen** 2016-12-20 17:50 UTC
Labels: duplicate
