### ISSUE TITLE
Intellisense from output folder

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#1134] opened 2017-03-28 17:41 UTC
_From @AbubakerB on October 17, 2016 19:10_

Hi guys,

I don't know if this is the correct place to raise this but I'm trying to get intellisense from razor files in non-web projects and its just not working.
I'm using tools like RazorEngine/RazorTemplate/RazorLight and the only way to get intellisense is to copy their dlls to the \bin folder. I read that the reason for this is because VS only looks at the \bin directory because, of course, that's the default output folder for web-projects.
But for example, console apps, have their output in \bin\debug or \bin\release. Is there a way to make this work atm (with VS2015.3)? Or is there a reason to why it only looks in the bin folder?
If it's not already fixed, could it be fixed?

I've searched everywhere for an answer on this but all I can find are people saying copy to bin folder.

_Copied from original issue: aspnet/RazorTooling#103_

**Comment by Eilon** [comment] 2017-03-28 17:41
_From @NTaylorMullen on October 17, 2016 21:28_

@AbubakerB there currently is not a way to do this by default for non-web projects. Sorry that there's not a better answer 😢

**Comment by Eilon** [comment] 2017-03-28 17:41
_From @AbubakerB on October 17, 2016 21:41_

That's alright, thanks for the response.
Would it be possible to make this work for the upcoming VS "15"?

**Comment by Eilon** [comment] 2017-03-28 17:41
_From @NTaylorMullen on October 17, 2016 21:58_

We're currently rethinking the way the Razor editor works and have started prototyping. In this "new" world having support for class libraries would definitely be something on our radar.

**Comment by Eilon** [comment] 2017-03-28 17:41
_From @AbubakerB on October 17, 2016 22:7_

Awesome! Looking forward to it!

**Comment by rynowak** [comment] 2017-04-25 15:24
Dupe of #1136

**Closed by rynowak** 2017-04-25 15:24 UTC
