### ISSUE TITLE
Throwing an exception from a TagHelper causes web server crash

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/Razor#607] opened 2015-11-16 16:11 UTC
Version: latest RC1, runtime Clr-x86-1.0.0-rc1-16048

TagHelper code:
```c#
public class MyTagHelper : TagHelper {

    public bool Throw { get; set; }

    public override async void Process(TagHelperContext context, TagHelperOutput output) {
        if(Throw)
            throw new Exception("some prerequisites failed");
        else
            await output.GetChildContentAsync();
    }

}
```

Markup:
```html
@addTagHelper "*, Samples"

<my>
    <my throw="true"></my>
</my>
```

What happens:

* Kestrel exist with an Unhandled Exception
* IISExpress displays "502.3 - CGI application encountered an error and the server terminated the process"

**Comment by danroth27** [comment] 2015-11-16 17:37
@NTaylorMullen please investigate and redirect as appropriate.

**Comment by NTaylorMullen** [comment] 2015-11-17 17:24
Hey @AlekseyMartynov good find! Turns out the reason why is due to your `async void` on the `Process` method. I'd recommend transitioning over to `ProcessAsync`. The root cause ended up being in the KestrelHttpServer so I've opened a bug there: https://github.com/aspnet/KestrelHttpServer/issues/398

Closing this one here since there's the Kestrel bug to track it.

**Closed by NTaylorMullen** 2015-11-17 17:24 UTC
Labels: investigate
