### ISSUE TITLE
No Intellisense at all

### ISSUE THREAD

**Issue by derpcoder** [aspnet/Razor#758] opened 2016-05-19 13:44 UTC
Hello,

I'm having issues with the Intellisense for Razor. It is not working at all, not Layout, not inject, not model, only tag helpers highlighting seems to be working..

I have the 
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    }
in the global dependencies and

    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
in tools, but still not working.

![untitled](https://cloud.githubusercontent.com/assets/225781/15396441/252f1ea6-1daa-11e6-8846-408467416f3d.png)

**Comment by NTaylorMullen** [comment] 2016-05-19 16:57
Closing this as duplicate of your [tooling issue](https://github.com/aspnet/Tooling/issues/504) (that's the better area for this issue).

**Closed by NTaylorMullen** 2016-05-19 16:57 UTC
