### ISSUE TITLE
"li" element was not closed.  All elements must be either self-closing or have a matching end tag.

### ISSUE THREAD

**Issue by qibucloud** [aspnet/Razor#1682] opened 2017-09-13 02:47 UTC
```@foreach (var item in contentlist)
{
        	<li><a href="#">
                    <i></i><font>@(item.Name)</font>
        	    <span>@item.UpdateTime.ToString("yyyy-MM-dd")</span></a>
               </li>
}

Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
index.cshtml(162,11): Error RZ9999: The "li" element was not closed.  All elements must be either self-closing or have a matching end tag.
index.cshtml(162,164): Error RZ9999: Encountered end tag "a" with no matching start tag.  Are your start/end tags properly balanced?
index.cshtml(162,168): Error RZ9999: Encountered end tag "li" with no matching start tag.  Are your start/end tags properly balanced?
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)```

**Comment by Eilon** [comment] 2017-09-13 16:16
@NTaylorMullen / @ajaybhargavb / @rynowak - any idea on this? Maybe a Razor parser bug? I can't see anything obviously wrong in the syntax above.

**Comment by ajaybhargavb** [comment] 2017-09-13 18:18
I tried but couldn't reproduce this. @qibucloud, could you include include more of your cshtml? It'll be helpful to know what scope your `<li>` lies in.

**Comment by ajaybhargavb** [comment] 2017-09-13 18:27
Also the line numbers in the errors don't seem to correspond to the razor code above. The errors are all on the same line (162) but the end tag for `a` and `li` are all on different lines.

**Comment by Eilon** [comment] 2017-09-13 21:01
Maybe an issue with line endings? How does Razor behave when a single file uses different line endings on different lines? I could see that confusing things...

E.g.:

```
{ CR
        	<li><a href="#"> CR
                    <i></i><font>@(item.Name)</font> CRLF
        	    <span>@item.UpdateTime.ToString("yyyy-MM-dd")</span></a> CRLF
               </li> CR
} CR
```

Or something like that.

**Comment by qibucloud** [comment] 2017-09-14 04:17
@Eilon @ajaybhargavb 
This is the wrong time cshtml, but now the test is no problem, thank you

```@{
    Layout = $"{Data.codepath}_公共框架.cshtml";
}
<!--banner-->
<div class="banner_pc">
    <div class="flexslider">
        <ul class="slides">
@{
var contentlist = Contents.GetList(Data, 0, "home-slide", 8);
@foreach (var item in contentlist)
{
    <li><a href="@(item.ContentLink)"><img src="@(item.Content_Pic)" alt="@(item.ContentName)"/></a></li>
}
}
        </ul>
    </div>
</div>
<div class="banner_sj">
    <div class="flexslider">
        <ul class="slides">
@foreach (var item in contentlist)
{
        <li><a href="@(item.ContentLink)"><img src="@(item.Content_sjPic)"></a></li>
}
        </ul>
    </div>
    <script type="text/javascript">
    jQuery(document).ready(function() {
      if(jQuery('.flexslider').length){
          jQuery('.flexslider').flexslider({
            animation: "slide",
            start: function(slider){
              jQuery('body').removeClass('loading');
            }
          });
      }
    });
    </script>
</div>
<!--hot_product-->
<div class="hot_product">
	<div class="hot_p_left">
    	<big>产品目录</big>
    	<ul class="tab_title">
@{
var navigations = Navigations.GetList(Data, 0, "products", 7);
foreach (var item in navigations)
{
<li><a href="@(Data.culture)/@(item.RoutingUrl).html"><i></i>@(item.NavigationName)</a></li>
}
}
        </ul>
    </div>
    <div class="hot_p_right">
		<div class="hot_p_name"><big>新品推荐</big><a href="@(Data.culture)/products.html"><img src="@(Data.sitepath)images/more.png" alt=""/></a></div>
        <div class="hot_p_img">
@foreach (var item in navigations)
{         <div class="t_con">
            <ul>
@foreach (var items in Contents.GetList(Data, 0, item.RoutingUrl, 4))
{
            	<li><a href="@(Data.culture)/@(items.RoutingUrl).html"><img src="/cut_185_157@(items.Content_Pic)" alt="@(items.ContentName)"/><em>@(items.ContentName)</em></a></li>
}
            </ul>
          </div>
}
    </div>
</div>
</div>
<script type="text/javascript">
    jQuery(".hot_product .t_con").slide({ mainCell:"ul",vis:4,prevCell:".sPrev",nextCell:".sNext",effect:"leftMarquee",interTime:50,autoPlay:true,trigger:"click"});
    jQuery(".hot_product").slide({titCell:".tab_title li",mainCell:".hot_p_img"});
</script>
<!--hezuo-->
<div class="hezuo">
	<div class="hezuo_name"><big>合作客户</big><a href="@(Data.culture)/kehu.html"><img src="@(Data.sitepath)images/more.png" alt=""/></a></div>
    <div class="img-scroll">
        <span class="prev"></span>
        <span class="next"></span>
        <div class="img-list">
            <ul>
@{
contentlist = Contents.GetList(Data, 0, "kehu", 8);
@foreach (var item in contentlist)
{
    <li><a href="@(item.ContentLink)" target="_blank"><img src="@(item.Content_Pic)" alt="@(item.ContentName)"/><span>@(item.ContentName)</span></a></li>
}
}
            </ul>
        </div>
    </div>
    <script type="text/javascript" src="@(Data.sitepath)js/qiehuan.js"></script>
</div>
<!--about_us-->
<div class="about_us">
	<div class="about">
		<div class="ab_name"><big>公司介绍</big><a href="@(Data.culture)/about.html"><img src="@(Data.sitepath)images/more.png" alt=""/></a></div>
        <div class="ab_nrong"><a href="@(Data.culture)/about.html">@Html.Raw(Data.ViewData["home-page-introduction"])</a></div>
	</div>
    <div class="equipment">
    	<div class="equi_name"><big>设备展示</big><a href="@(Data.culture)/canguan.html"><img src="@(Data.sitepath)images/more.png" alt=""/></a></div>
        <div class="equi_nr">
        <div id="demo">
            <div id="indemo">
                <div id="demo1">
                	<ul>
@{
contentlist = Contents.GetList(Data, 0, "canguan", 4);
@foreach (var item in contentlist)
{
<li><a href="@(Data.culture)/canguan.html"><img src="@(item.Content_Pic)" alt="@(item.ContentName)"/><span>@(item.ContentName)</span></a></li>
}
}
                    </ul>
                </div>
                <div id="demo2"></div>
            </div>
        </div>  
        <script>
        <!--
        var speed=20;
        var tab=document.getElementById("demo");
        var tab1=document.getElementById("demo1");
        var tab2=document.getElementById("demo2");
        tab2.innerHTML=tab1.innerHTML;
        function Marquee(){
        if(tab2.offsetWidth-tab.scrollLeft<=0)
        tab.scrollLeft-=tab1.offsetWidth
        else{
        tab.scrollLeft++;
        }
        }
        var MyMar=setInterval(Marquee,speed);
        tab.onmouseover=function() {clearInterval(MyMar)};
        tab.onmouseout=function() {MyMar=setInterval(Marquee,speed)};
        -->
        </script>
        </div>
    </div>
</div>
<!--intermediate-->
<div class="intermediate">
	<div class="news">
    	<div class="news_name"><big>最新动态</big><a href="@(Data.culture)/news.html"><img src="@(Data.sitepath)images/more.png" alt=""/></a></div>
        <ul>
@{
contentlist = Contents.GetList(Data, 1, "news", 7);
@foreach (var item in contentlist)
{
        	<li><a href="@(Data.culture)/@(item.RoutingUrl).html"><i></i><font>@(item.ContentName)</font><span>@item.UpdateTime.ToString("yyyy-MM-dd")</span></a></li>
}
}
        </ul>
    </div>
    <div class="news">
    	<div class="news_name"><big>技术文档</big><a href="@(Data.culture)/support.html"><img src="@(Data.sitepath)images/more.png" alt=""/></a></div>
        <ul>
@{
contentlist = Contents.GetList(Data, 0, "technical-documentation", 7);
@foreach (var item in contentlist)
{
        	<li><a href="@(Data.culture)/@(item.RoutingUrl).html"><i></i><font>@(item.ContentName)</font><span>@item.UpdateTime.ToString("yyyy-MM-dd")</span></a></li>
}
}
        </ul>
    </div>
    <div class="zhuti">
		<div class="zt1">
        	<div class="zt1_left"><img src="@(Data.sitepath)pic/zt1.jpg" alt=""/></div>
            <div class="zt1_right"><big>控制板方案开发提供商</big><small>客户需求+工程确认+开发设计+布板打样+焊板调试+客户确认</small></div>
        </div>
    	<div class="zt2">
        	<div class="zt2_left"><big>专业控制板生产厂</big><small>自动印锡+SMT(0201 BGA)+10温区回流焊+AOI检查+DIP双波峰焊+成品QC+精细维修</small></div>
            <div class="zt2_right"><img src="@(Data.sitepath)pic/zt2.jpg" alt=""/></div>
        </div>
    	<div class="zt3">
        	<div class="zt3_left"><img src="@(Data.sitepath)pic/zt3.jpg" alt=""/></div>
            <div class="zt3_right"><big>一站式开发生产提供商</big><small>研发+贴片+插件=成品控制板</small></div>
        </div>
    </div>
</div>
<!--links-->
<div class="links">
	<div class="links_name"><big>友情链接</big></div>
	<div class="links_nr">@Html.Raw(Data.ViewData["friendship-link"])</div>
</div>
@section scripts{

}
```

**Comment by Eilon** [comment] 2017-09-14 04:44
@qibucloud so everything is working now?

**Comment by qibucloud** [comment] 2017-09-14 05:44
@Eilon Yes, yes

**Comment by ajaybhargavb** [comment] 2017-09-14 18:52
Closing as there is no issue.

**Closed by ajaybhargavb** 2017-09-14 18:52 UTC
Labels: investigate
