### ISSUE TITLE
Error rzc generate exited with code -2147450749

### ISSUE THREAD

**Issue by AyoubHaggui** [aspnet/Razor#2630] opened 2018-10-04 14:51 UTC
I didn't find the matching error code anywhere, I'm a running a net core app 2.1 I use VS2017 Enterprise.  This is the error message I get:
`
Severity	Code	Description	Project	File	Line	Suppression State
Error		rzc generate exited with code -2147450749.	BotFlow.Portal	C:\Users\SP-Ayoub\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	103	
`
This is the my .csproj:

```xml
<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\netcoreapp2.0\BotFlow.Portal.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="8.0.100" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="8.0.100" />
    <PackageReference Include="FluentValidation.ValidatorAttribute" Version="8.0.100" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="2.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <!-- Files not to publish (note that the 'dist' subfolders are re-added below) -->
    <Compile Remove="ClientApp\dist\**" />
    <Compile Remove="ClientApp\environments\**" />
    <Content Remove="ClientApp\**" />
    <EmbeddedResource Remove="ClientApp\dist\**" />
    <EmbeddedResource Remove="ClientApp\environments\**" />
    <None Remove="ClientApp\dist\**" />
    <None Remove="ClientApp\environments\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ClientApp\angular.json" />
    <Content Include="ClientApp\package-lock.json" />
    <Content Include="ClientApp\package.json" />
    <Content Include="ClientApp\src\tsconfig.app.json" />
    <Content Include="ClientApp\src\tsconfig.spec.json" />
    <Content Include="ClientApp\src\tslint.json" />
    <Content Include="ClientApp\tsconfig.json" />
    <Content Include="ClientApp\tslint.json" />
  </ItemGroup>
```

**Comment by mkArtakMSFT** [comment] 2018-10-04 17:09
Thanks for contacting us, @AyoubHaggui.
@pranavkm, is there enough details here or do you need a repro to investigate this?

**Comment by AyoubHaggui** [comment] 2018-10-04 17:14
Thanks a lot, I fixed this by uninstalling net core and removing the installation folder and reinstalling the x64 version

**Comment by mkArtakMSFT** [comment] 2018-10-05 16:04
Glad to hear that, @AyoubHaggui.
Do you think it was related to x86 installation (as I understand that was what you had before) or was it related to some unrelated issue caused by some misconfiguration/damage somewhere else?

**Comment by AyoubHaggui** [comment] 2018-10-05 16:33
I had the same issue installing the x86 version on two machines with x64 architecture, I believe it was related to the x86 version not fitting the machine architecture

**Comment by mkArtakMSFT** [comment] 2018-10-08 15:54
@pranavkm, can you please investigate this? Not sure how much we can investigate though.

**Comment by mkArtakMSFT** [comment] 2018-10-22 16:28
@pranavkm, if there is no enough data for you to investigate this, go ahead and close this.

**Comment by pranavkm** [comment] 2018-10-26 17:53
Fair enough. We can reopen this issue if other users run in to this.

**Closed by pranavkm** 2018-10-26 17:53 UTC
Labels: investigate

**Comment by aghouraf** [comment] 2018-11-30 00:18
I had the same issue installing the x86 version and the  x64 version

**Comment by aghouraf** [comment] 2018-11-30 00:20
I had a same problem installing x86 and x64 versions on the same x64 machine
