### ISSUE TITLE
@Html.DisplayNameFor, @Html.DisplayFor...etc with types from class libraries causes exception

### ISSUE THREAD

**Issue by bhalkett** [aspnet/Razor#763] opened 2016-05-24 17:37 UTC
First, I got the sample code that @ShadowDancer linked in the first post [here](https://github.com/aspnet/Razor/issues/755). I verified that the code fails when the Index.cshtml razor file is dynamically compiled at runtime.

Second, I got the code working by adding the following workaround code to the startup.cs file:
<div>
<pre>
services.AddMvc()
        .AddRazorOptions(options =>
        {
            var previous = options.CompilationCallback;
            options.CompilationCallback = context =>
            {
                previous?.Invoke(context);
                context.Compilation = context.Compilation.AddReferences(MetadataReference.CreateFromFile(typeof(MyClass).Assembly.Location));
            };
        })
</pre>
</div>

Finally, I broke the code again by adding the following property to the Dog class:

 <div>
<pre>
       public string Name { get; set; }
</pre>
</div>

And then the contents of the Index.cshtml with the following:
<div>
<pre>
@model ClassLibrary.Dog

@Html.DisplayNameFor(model => model.Name)
@Html.DisplayFor(model => model.Name)
</pre>
</div>

Here's the error message I get:
![88ebd04a-211c-11e6-983c-2fd1573fde58](https://cloud.githubusercontent.com/assets/6025169/15513596/20352cda-219a-11e6-8f71-f36f73fd2b4d.png)

**Comment by rwasef1830** [comment] 2016-05-24 18:07
I'm also getting this but on a view that has a ```@model ``` directive and an ```<input asp-for="Property.SubProperty">```. However ```<input asp-for="AnotherProperty">``` works.

**Comment by Eilon** [comment] 2016-05-24 19:47
@pakrym any idea about this?

**Comment by bhalkett** [comment] 2016-05-24 20:00
@rwasef1830 - Could you elaborate on your statement above that <code>&lt;input asp-for="AnotherProperty"&gt;</code> works.  An example would be great.  

I couldn't get any of the <code>&lt;input asp-for...</code> TagHelpers to work.

**Comment by dougbu** [comment] 2016-05-24 21:02
This issue is likely a dupe of aspnet/Mvc#4497. I plan to test whether @pranavkm's change to enable application parts as additional references for MVC Razor compilation solves this case.

**Comment by rwasef1830** [comment] 2016-05-24 21:04
Project1ClassLibrary.csproj:
```
class ViewModel 
{
    public string VmProperty { get; set; }
    public Dto DtoProperty { get; set; }
}

class Dto
{
    public string Name { get; set; }
}
```

Project2WebApp.xproj
```
@model ViewModel

<input asp-for="VmProperty" /> <!-- Works -->
<input asp-for="DtoProperty.Name" /> <!-- Causes the exception reported in this bug -->
```

If ```ViewModel`` and ```Dto``` are both in ```Project2WebApp.xproj```, both tag helpers work, otherwise, the workaround in #755 must be applied to avoid the reference issue, and then the exception in this bug report will appear, unless the second tag helper is commented out.

**Comment by bhalkett** [comment] 2016-05-25 00:29
@dougbu - Yes, it looks like a duplication.  Please let me know if/when there is code I can test.  Thanks!

**Comment by Eilon** [comment] 2016-05-25 01:06
Ok, closing as a dup of https://github.com/aspnet/Mvc/issues/4497 then.

**Closed by Eilon** 2016-05-25 01:06 UTC
