### ISSUE TITLE
Desktop MsBuild timeout on AppVeyor - Build_SimpleMvc_UsingDesktopMSBuild_CanBuildSuccessfully 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2115] opened 2018-02-27 17:43 UTC
```
Server pid:4976 shut downFailed to delete directory C:\Users\appveyor\AppData\Local\Temp\1\Razor\yuh44eu2.csq, trying again.
[xUnit.net 00:01:42.0724316]     Build_SimpleMvc_UsingDesktopMSBuild_CanBuildSuccessfully [FAIL]
[xUnit.net 00:01:42.0730358]       System.TimeoutException : command '$C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\MSBuild.exe /restore /t:Build /p:Configuration=Release /p:RazorCompileOnBuild=true' timed out after 00:01:00.
[xUnit.net 00:01:42.0750736]       Stack Trace:
[xUnit.net 00:01:42.0768967]         C:\projects\razor\test\Microsoft.AspNetCore.Razor.Design.Test\IntegrationTests\MSBuildProcessManager.cs(79,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass0_0.<RunProcessAsync>b__0(Task t)
[xUnit.net 00:01:42.0775899]            at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
[xUnit.net 00:01:42.0778976]            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, 
```

The build in question - https://ci.appveyor.com/project/aspnetci/razor/build/1.0.4144

**Comment by pranavkm** [comment] 2018-02-27 17:43
cc @ajaybhargavb

**Comment by ajaybhargavb** [comment] 2018-02-27 18:07
Wonder why this would time out. It's not even using the server.

**Comment by pranavkm** [comment] 2018-02-27 18:10
Hmm, I wonder if the server error is from a different test and this test failure was a different flakiness

**Comment by ajaybhargavb** [comment] 2018-02-27 18:13
In that case I expect the test that produced the server error to also fail because we do RazorForceBuildServer=true. But that doesn't seem to be happening

**Comment by ajaybhargavb** [comment] 2018-02-28 03:17
This has been failing on Appveyor for a long time now. But it doesn't fail on other windows machines. I suspect the desktop MsBuild version used by Appveyor is old.

**Comment by rynowak** [comment] 2018-02-28 03:41
Does the oldness of MSBuild explain the timeout? or would that fail in some other way?

**Comment by ajaybhargavb** [comment] 2018-02-28 18:09
I trying to find out the exact version Appveyor is using. But yea I can't think of any other reason that would make only desktop MsBuild timeout and that too only on Appveyor.

**Comment by ajaybhargavb** [comment] 2018-02-28 20:10
Appveyor is using 15.5.178.35674

**Comment by pranavkm** [comment] 2018-02-28 20:43
I have this on my box - 15.5.180.51428. The one on AppV doesn't seem super old

**Comment by ajaybhargavb** [comment] 2018-03-06 00:35
This is an unknown and I haven't been successful at reproducing this locally. Costing this as M for now. I wouldn't be surprised if it turned out to be an S.

**Comment by ajaybhargavb** [comment] 2018-03-06 18:54
@mkArtakMSFT, can this be closed now that we no longer run Appveyor builds? We can re-open if we see this failure on any other builds.

**Comment by mkArtakMSFT** [comment] 2018-03-13 18:26
As this seems to be just AppVeyour thing, and we can't even repro it, let's just close this. Especially when AppVeyour is disabled for this repo already.

**Closed** 2018-03-13 18:26 UTC
Labels: 1 - Ready, area: Build, cost: M
