### ISSUE TITLE
Error: Invalid name for a preprocessing symbol; '' is not a valid identifier

### ISSUE THREAD

**Issue by fmdufour** [aspnet/Razor#1686] opened 2017-09-15 20:28 UTC
I have recently migrated from ASP.NET Core 1.1.X to ASP.NET Core 2,  when I run my app locally everything works fine, but when running on Azure App Service I receive the following error on Razor Compilation:

```
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

Invalid name for a preprocessing symbol; '' is not a valid identifier
#pragma checksum "D:\home\site\wwwroot\Views\Register\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3683385b8f60453d746a40cc4d8b7a6f260ae5ca"
```

I tried to find a solution but couldn't find any,
Can anyone help me?

Thank you

**Comment by rynowak** [comment] 2017-09-15 21:44
We've seen a similar bug to this in the past https://github.com/dotnet/sdk/issues/1364

I'm unsure what exactly could be the cause for you.

Can you share your `.csproj`?

**Comment by fmdufour** [comment] 2017-09-16 23:43
I fixed it by changing from NETCOREAPP1_1 to NETCORE2_0:

`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Development|AnyCPU'">
    <DefineConstants>Development;NETCOREAPP1_1</DefineConstants>
    <DebugType>Full</DebugType>
    <DebugSymbols>True</DebugSymbols>
  </PropertyGroup>`

to:

`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Development|AnyCPU'">
    <DefineConstants>Development;NETCOREAPP2_0</DefineConstants>
    <DebugType>Full</DebugType>
    <DebugSymbols>True</DebugSymbols>
  </PropertyGroup>`

Thanks!

**Comment by rynowak** [comment] 2017-09-21 22:04
Closing this as a dupe of dotnet/sdk#1364

**Closed by rynowak** 2017-09-21 22:04 UTC

**Comment by CGSgeosite** [comment] 2018-03-31 04:20
No characters after @page

**Comment by rynowak** [comment] 2018-04-02 20:28
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
