### ISSUE TITLE
Razor generator misbehavior

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/Razor#329] opened 2015-03-21 23:32 UTC
Hi,

The ASP.NET MVC Razor engine generates the following for a boolean field:

    <input class="form-control check-box" data-val="true"
      data-val-required="The IsHappy field is required."
      id="Properties_IsHappy" name="Properties.IsHappy"
      type="checkbox" value="false">

Razor code:

    @Html.EditorFor(model => model.IsHappy)

So first of all, the `check-box` class, is supposed to be `checkbox` according to the [docs](http://getbootstrap.com/css/#checkboxes-and-radios "Checkboxes and radios").  
Besides, it's also classed with the `.form-control` class, which sets its width to 100%, making it look like this:

![enter image description here][1]

According to the [bootstrap CSS docs][2] on the `.form-control` class:
>Textual `<input>`s only
Avoid using `<select>` elements here as they cannot be fully styled in WebKit browsers.  

What I do instead is changing all the generated views' `EditorFor` to:

    @Html.CheckBoxFor(model => model.HasDiabetes, new { @class = "checkbox" })

But either the razor view generator should be fixed and generate `CheckBoxFor` for `bool`s, or the `EditorFor` should omit the `.form-control` class, which doesn't belong on `checkbox`es.

Please take a look at [this](https://github.com/twbs/bootstrap/issues/16123) issue at the bootstrap repo.

  [1]: http://i.stack.imgur.com/PABV6.png
  [2]: http://getbootstrap.com/components/#textual-%3Cinput%3Es-only

**Comment by dougbu** [comment] 2015-03-22 00:20
@weitzhandler please see the similar aspnet/Mvc#1135 issue.  this is not a Razor issue and we would likely consider your report a duplicate of aspnet/Mvc#1135.

FYI we generate the classes we do in `EditorFor` for compatibility with MVC 5 and earlier.  we could break applications ported from MVC 5 which configure the `check-box` class and expect that CSS to be reflected on the page. in addition you described a fairly simple workaround to pick up the Bootstrap class.

separately the MVC 6 code does _not_ add a `form-control` class anywhere.  if this was not the result of a `"htmlAttributes"` key in the `ViewData` or `additionalViewData` argument to `EditorFor()`, please open a bug in the MVC repo and provide a small sample (preferably a GitHub repo) demonstrating that addition.

(minor nit: the Bootstrap `checkbox` attribute should be applied to a `<div/>` surrounding the `<label/>` and `<input/>`, not the `<input/>` element itself)

**Closed by dougbu** 2015-03-22 00:20 UTC

**Comment by weitzhandler** [comment] 2015-03-22 00:24
@dougbu Are you familiar with the aspnet/Mvc repo?  
Can you please show me where in the MVC the view generation and HTML rendering happens?

**Comment by rynowak** [comment] 2015-03-22 00:33
>separately the MVC 6 code does not add a form-control class anywhere. if this was not the result of a "htmlAttributes" key in the ViewData or additionalViewData argument to EditorFor(), please open a bug in the MVC repo and provide a small sample (preferably a GitHub repo) demonstrating that addition. 

Or, option 3 is that our template are doing something janky. @rustd thoughts?

**Comment by dougbu** [comment] 2015-03-22 00:34
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Rendering/Html/DefaultEditorTemplates.cs#L38 generates the `check-box` class.

**Comment by weitzhandler** [comment] 2015-03-22 00:49
Thank you!

**Comment by weitzhandler** [comment] 2015-03-22 00:53
So why shouldn't it we have the class dependent on the MVC version? And if bootstrap is provided with that version (or another way of identifying bootstrap), `checkbox` class should be generated instead.

**Comment by dougbu** [comment] 2015-03-22 01:08
> another way of identifying bootstrap

server-side generation does not know which CSS files will be included in the final page

> `DefaultEditorTemplates` should be pluggable

`DefaultEditorTemplates` can be completely overridden as you choose.  create a Shared/EditorTemplates/Boolean.cshtml template.

**Comment by weitzhandler** [comment] 2015-03-22 01:11
Yeah. That's what I did.

And in reference to that, it was hard for me to know exactly what the system is generating before I start overriding it, so a good suggestion would be when generating a view, being able to provide any class in the BCL (i.e. `System.Boolean`), and the razor engine should generate the default content as a starting point.
