### ISSUE TITLE
@using directive IntelliSense does not auto complete

### ISSUE THREAD

**Issue by jbagga** [aspnet/Razor#1460] opened 2017-06-22 18:53 UTC
When trying to add a namespace:

`@using WebApplication1.Models`

No IntelliSense appears for WebApplication1 at all. Models appears in the IntelliSense list but selecting it does not autocomplete the statement. (no text is appended to the statement)

CLI version: 2.0.0-preview2-006497
VS: 26621.2.d15rel

cc @NTaylorMullen

**Comment by ajaybhargavb** [comment] 2017-08-29 19:52
Duplicate of https://github.com/aspnet/Razor/issues/1221.

**Comment by ajaybhargavb** [comment] 2017-08-29 19:58
Actually, we handle using directives differently. Fix for #1221 doesn't cover this.

**Comment by dougbu** [comment] 2017-09-12 23:19
On a related note (I suspect), extra whitespace after the `@using` directive loses IntelliSense completely. E.g. `@using  System` is displayed in white rather than colourized.

**Comment by Andrzej-W** [comment] 2018-05-13 18:30
My issue #2344 was closed as duplicate of this one but I'm not sure it is really a duplicate. In my example intellisense works, I'm able to select something and it is inserted into text editor **but in wrong place**. In this issue selected text is not inserted at all. The difference is that in my case I already have a few `@using` statements and the one I'm using in auto complete is longer than the one already present in text editor. Make sure that after fixing this bug #2344 works correctly.

**Comment by NTaylorMullen** [comment] 2018-05-13 19:42
@Andrzej-W you're right. sorry, i'll re-open your other issue and continue the conversation there.

**Comment by NTaylorMullen** [comment] 2018-05-16 18:32
@ToddGrun investigated this issue and here's the findings:

When typing a `using` statement that semi-duplicates an existing using (the other using can be from the same file, a default using or one imported from a `_ViewImports.cshtml`) we end up doing the following:

Cursor is at | and a _ViewImports is already `@using WebApplication1`
```
@using WebApplication1|
```

- Type `.` and then complete anything

We end up forcing a reparse on the `.` which results in our using de-duplication logic re-generating the `using WebApplication1` behind the scenes and changing the location of the projection of our current `@using`. Because of this Roslyn auto-completes whatever is typed in the hidden C# buffer for where the `@using` originally was which ends up not mapping to where we've regenerated the code.

In @Andrzej-W's case, there's a similar using statement in the same file which is projected; because of this Roslyn auto-completes the statement in the similar using's location because of how we re-generate the C#.

**Comment by NTaylorMullen** [comment] 2018-06-15 20:18
d6f3a1bd223ef9d7dc56b16f1da6bdb88fb0264f

**Closed by NTaylorMullen** 2018-06-15 20:18 UTC
Labels: 3 - Done, bug, cost: S
