### ISSUE TITLE
Multiline string interpolation fails when method with string arguments used

### ISSUE THREAD

**Issue by travislaynewilson** [aspnet/Razor#1472] opened 2017-06-27 19:22 UTC
When attempting to create a JSON-LD string using multiline, string interpolation and a method with a string argument, the compiler throws an error just before the last quotation mark of the returning string.

Moving the string format to a single line fixes the issue, and removing the method argument fixes the issue. You can also pass a blank string to make it work.

```
@Model.Locations.Select(location => $@"
    {{
        ""id"": ""{Url.Action("Index")}""
    }}"
)
```

Error: 
```
Unterminated string literal. Strings that start with a quotation mark (") must be terminated before the end of the line. However, strings that start with @ and a quotation mark (@") can span multiple lines.
```

**Comment by NTaylorMullen** [comment] 2017-06-27 21:46
Duplicate of https://github.com/aspnet/Razor/issues/401

**Closed by NTaylorMullen** 2017-06-27 21:46 UTC
Labels: duplicate
