### ISSUE TITLE
Compilation/restore failing (via build.cmd) - The target "Restore" does not exist in the project

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Razor#1726] opened 2017-10-18 11:19 UTC
I cloned the repo and run `build.cmd /t:Restore` (for `build.cmd` it's the same result). 
It mostly works but fails on Microsoft.VisualStudio.RazorExtension.csproj with MSB4057 ("The target "Restore" does not exist in the project") error:
```
D:\Work\Repos\aspnet\Razor.my>build.cmd /t:Restore
Using KoreBuild 2.1.0-preview1-15532
WARNING: dotnet found on the system PATH is 'C:\Program Files\dotnet\dotnet.exe' but KoreBuild will use 'C:\Users\Sergei
Dorogin\.dotnet\x64\dotnet.exe'.
WARNING: Adding 'C:\Users\Sergei Dorogin\.dotnet\x64' to system PATH permanently may be required for applications like Visual
Studio or VS Code to work correctly.
Adding C:\Users\Sergei Dorogin\.dotnet\x64 to PATH
.NET Core runtime 2.0.0 is already installed. Skipping installation.
.NET Core SDK 2.1.0-preview1-007042 is already installed. Skipping installation.
>>> dotnet.exe msbuild @D:\Work\Repos\aspnet\Razor.my\artifacts\msbuild\msbuild.rsp
  Using lineup Internal.AspNetCore.Universe.Lineup 2.1.0-preview1-27331
  Using lineup Internal.AspNetCore.Partners.Lineup 2.1.0-preview1-27331
  Pinned 200 package(s) from 2 lineup(s) in 1548ms

<lots of restore skipped>

D:\Work\Repos\aspnet\Razor.my\tooling\Microsoft.VisualStudio.RazorExtension\Microsoft.VisualStudio.RazorExtension.csproj : error MSB4057: The target "Restore" does not exist in the project. [C:\Users\Sergei Dorogin\.dotnet\buildtools\korebuild\2.1.0-preview1-15532\KoreBuild.proj]
D:\Work\Repos\aspnet\Razor.my\build\VSIX.targets(29,5): error MSB3073: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" "D:\Work\Repos\aspnet\Razor.my/tooling\Microsoft.VisualStudio.RazorExtension\Microsoft.VisualStudio.RazorExtension.csproj" /t:Restore /v:m /p:BuildNumber=t000" exited with code 1. [C:\Users\Sergei Dorogin\.dotnet\buildtools\korebuild\2.1.0-preview1-15532\KoreBuild.proj]
```

What did I miss?

**Comment by NTaylorMullen** [comment] 2017-10-18 17:42
@evil-shrike does your local copy contain [this commit](https://github.com/aspnet/Razor/commit/0241e8ff8b87537a31f75750e7fc0ac94a340645) from yesterday?

**Comment by Eilon** [comment] 2017-10-19 17:25
Also cc @natemcmaster in case you have ideas.

**Comment by natemcmaster** [comment] 2017-10-19 17:29
What version of VS is installed? You need at least 15.3.

Also, it looks like you're using the BuildTools SKU of VS. I'm not sure if VSIX development is available in this SKU.

**Comment by evil-shrike** [comment] 2017-10-20 01:33
sure, 15.3
> it looks like you're using the BuildTools SKU of VS

I have several VS and BuildTools, I guess they are in conflict and it causes the error.

**Comment by natemcmaster** [comment] 2017-10-20 16:18
Ok. I assume the problem is here then:

https://github.com/aspnet/Razor/blob/b064a28dcfb1c9e1b9c694022b67e6393f2f72db/build/VSIX.targets#L14-L17

This globbing pattern picks up the first VS it finds alphabetically. BuildTools > Community > Enterprise. @jkotalik and I are currently looking into making our build tools smarter about which version of VS they pick using the vswhere.exe tool, but this work is not done yet. See https://github.com/aspnet/BuildTools/issues/428

**Comment by rynowak** [comment] 2017-10-20 16:34
@natemcmaster I don't want users to be blocked by this though - do you think it would work to add a `/p:SuppressRazorVSIX=true` or some such property until that work can be completed?

**Comment by natemcmaster** [comment] 2017-10-20 16:49
Yeah, that sounds good. We did that on the rel/2.0.1 branch and called it `/p:BuildVSIX=false`

**Comment by rynowak** [comment] 2017-10-20 19:49
Cool, I'll send a PR to that effect

**Comment by rynowak** [comment] 2017-10-20 23:34
@evil-shrike  - I've merged this now https://github.com/aspnet/Razor/pull/1731

Please let us know if this solves the problem:
```
.\build.cmd /p:BuildVSIX=false
```

**Comment by evil-shrike** [comment] 2017-10-20 23:55
@rynowak works great, thanks

**Comment by rynowak** [comment] 2017-10-21 00:20
OK cool, I'm going to close this then. Let us know if you run into any other issues.

**Closed by rynowak** 2017-10-21 00:20 UTC
Labels: investigate
