### ISSUE TITLE
RazorSdk_UsesUseSharedCompilationToSetDefaultValueOfUseRazorBuildServer fails on OSX High Sierra containing VS for Mac.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2220] opened 2018-03-26 18:06 UTC
```
Failed   RazorSdk_UsesUseSharedCompilationToSetDefaultValueOfUseRazorBuildServer
Error Message:
 System.TimeoutException : command '$dotnet msbuild /restore /p:_RazorBuildServerPipeName=4ec0f162-6a02-42b0-ae53-2e14f9230925 /t:Build /p:Configuration=Debug /t:_IntrospectUseRazorBuildServer /p:UseSharedCompilation=false' timed out after 00:01:00.
Stack Trace:
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass0_0.<RunProcessAsync>b__0(Task t) in /Users/ntaylormullen/Documents/GitHub/Razor/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/MSBuildProcessManager.cs:line 80
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.BuildIntrospectionTest.<RazorSdk_UsesUseSharedCompilationToSetDefaultValueOfUseRazorBuildServer>d__3.MoveNext() in /Users/ntaylormullen/Documents/GitHub/Razor/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/BuildIntrospectionTest.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ryanbrandenburg** [comment] 2018-04-03 16:53
[Here's](http://aspnetci/viewLog.html?buildId=438882&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) an example failing build.

**Comment by ryanbrandenburg** [comment] 2018-04-03 16:54
Thanks for filing this Taylor! If you could do me a favor and add things like this to the Infrastructure project when you create them that would help me keep track of everything. I'll send out an email letting everyone know.

**Comment by NTaylorMullen** [comment] 2018-04-03 17:32
> Thanks for filing this Taylor! If you could do me a favor and add things like this to the Infrastructure project when you create them that would help me keep track of everything. I'll send out an email letting everyone know.

Definitely good to know! Will do!

**Comment by ajaybhargavb** [comment] 2018-04-03 18:28
I investigated this and this seems to be a test issue. `dotnet build` with and without `UseSharedCompilation=false` works as expected.
This is probably some MsBuild and OSX test flakiness like https://github.com/aspnet/Razor/issues/2219.

**Comment by ajaybhargavb** [comment] 2018-05-24 18:58
After more investigation here is what I found,
- The feature itself works as expected
- Can't reproduce now locally on my Mac or on the CI
- This test by itself was never flaky
- This failure was part of a group of test failures with the same error which could be an issue with the SDK at that time (This test isn't special)
- This test wasn't disabled and this particular failure hasn't happened since

Considering the above points, I am closing this issue.

cc @pranavkm who has more context on this test. Please re-open if you feel otherwise.

**Closed by ajaybhargavb** 2018-05-24 18:58 UTC
Labels: 2 - Working, cost: S, investigate, task
