### ISSUE TITLE
Anchor tags causing exceptions on sections and nested layouts

### ISSUE THREAD

**Issue by erandros** [aspnet/Razor#453] opened 2015-07-17 15:45 UTC
I have a `_Layout` layout, a `_Sublayout` and a `Index.cshtml`. Each references the previous as its layout.  
When a section rendered in `_Sublayout` is defined in `Index` with just at least one anchor tag on it, I get a NullReferenceException.

Is this just me?

**Comment by dougbu** [comment] 2015-07-17 19:34
@erandros could you please provide more information? For example, what DNX version are you using?

If you are using Beta 5 or earlier i.e. are not on the bleeding edge, this bug is likely a duplicate of aspnet/Razor#412. Since that bug was fixed in Beta 6, you may want to try your scenario after executing `dnvm upgrade -u` and changing `project.json` files to use the very latest e.g. `"Microsoft.AspNet.Mvc": "6.0.0-*"`.

**Comment by danroth27** [comment] 2015-07-22 17:15
@dougbu Are you able to reproduce this?

**Comment by erandros** [comment] 2015-07-22 17:36
@dougbu The bug stopped happening when I started using newer versions of dnx. I was on 4.5.1. Thanks.

**Comment by dougbu** [comment] 2015-07-22 18:26
@danroth27 think we can close this. Given @erandros's success now, was likely a dupe of aspnet/Razor#412

**Closed** 2015-07-22 19:58 UTC
Labels: investigate
