### ISSUE TITLE
View failing to compile with missing referece

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Razor#2281] opened 2018-04-16 16:50 UTC
Since this commit exactly, as the build before was working fine.
https://github.com/aspnet/Razor/commit/95835d6c37c108ae0788f49ccc0d17f3ba20586e

```
[03:19:28.096]       Connection id "0HLD2DA5SCIB4", Request id "0HLD2DA5SCIB4:000000D5": An unhandled exception was thrown by the application.
[03:19:28.096] System.InvalidOperationException: Cannot find reference assembly 'Dapper.dll' file for package Dapper.Reference
[03:19:28.096]    at Microsoft.Extensions.DependencyModel.Resolution.ReferenceAssemblyPathResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
[03:19:28.096]    at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
[03:19:28.096]    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
[03:19:28.096]    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
[03:19:28.096]    at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
[03:19:28.096]    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
[03:19:28.096]    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
[03:19:28.096]    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
[03:19:28.096]    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
[03:19:28.096]    at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
[03:19:28.096]    at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
[03:19:28.096]    at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
[03:19:28.096]    at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
[03:19:28.121]    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
[03:19:28.121]    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
[03:19:28.121] --- End of stack trace from previous location where exception was thrown ---
[03:19:28.121]    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
[03:19:28.121]    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
[03:19:28.121]    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
[03:19:28.121]    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
[03:19:28.121]    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
[03:19:28.122]    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
[03:19:28.122]    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
[03:19:28.122]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[03:19:28.122] fail: Microsoft.AspNetCore.Server.Kestrel[13]
```

With this project https://github.com/aspnet/benchmarks/blob/dev/src/Benchmarks/Benchmarks.csproj with `TargetFramework == "netcoreapp2.1"`

**Comment by pranavkm** [comment] 2018-04-16 20:56
This stems from a known regression in the Sdk: https://github.com/dotnet/sdk/issues/2121 that's being addressed for rc1. Closing since there's nothing further we can do here.

**Closed by pranavkm** 2018-04-16 20:56 UTC
Labels: external
