### ISSUE TITLE
"Templates can be used only with field access..." error not displayed in VS

### ISSUE THREAD

**Issue by pakrym** [aspnet/Razor#1570] opened 2017-07-19 20:55 UTC
1. File->New->Web App
2. Go to Index.cshtml
3. Add tag helper with `ModelExpression` attribute
4. Use it and set it to unsupported expression type (`"A" + "B"`)

Expected: error squiggly in VS

Actual: no errors in VS, fails at runtime

**Comment by rynowak** [comment] 2017-08-08 04:49
@ajaybhargavb please investigate

**Comment by ajaybhargavb** [comment] 2017-09-08 21:44
I investigated this and looks like razor might not have enough information in design time to make this a design time error.

For example, in this ModelExpression attribute `for`,
```HTML
<test for="StringProp+1"></test>
```
the generated code looks like this,
```C#
__WebApplication5_TagHelpers_TestTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.StringProp+1);
```
which is valid c# and compiles successfully. It is only caught at runtime [here](https://github.com/aspnet/Mvc/blob/a23307e2b1e7934e2c8d69774cda1b36778f697b/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ExpressionMetadataProvider.cs#L80) in Mvc.
This seems to be more of a "by design". @rynowak @NTaylorMullen thoughts on if we want to come up with some sort of workaround for this?

**Comment by rynowak** [comment] 2017-09-11 14:49
I think this is a won't fix then. We don't attempt to do deep analysis and verification of these expressions and we don't want to.

Someone scream if you think we should care about this.

**Closed by rynowak** 2017-09-11 14:49 UTC
Labels: 2 - Working
