### ISSUE TITLE
Title attribute in <a> element looses Dropdown Intellisense when a TagHelper is used

### ISSUE THREAD

**Issue by jmalatia** [aspnet/Razor#839] opened 2016-10-29 15:45 UTC
When writing a `title` attribute in an `<a>` element, you loose Dropdown Intellisense, after the first level, when a TagHelper is used.

Down down box IntelliSense works fine for this standard HTML in a Razor View:
![image](https://cloud.githubusercontent.com/assets/5606334/19830665/3c6afc3c-9dc2-11e6-9b66-d58a2706a81b.png)
 
 
  
Down down box IntelliSense works OK for the initial first-level `@i`  when adding a TagHelper into the <a> element:
![image](https://cloud.githubusercontent.com/assets/5606334/19830681/77273db8-9dc2-11e6-8fad-27f915fddaee.png)
  
 
 
But Dropdown IntelliSense does not show for any of the next levels when a TagHelper is used in the same <a> element (the next level should popup after the `.` is pressed --- and it does not):
![image](https://cloud.githubusercontent.com/assets/5606334/19830692/adaa229c-9dc2-11e6-8d97-accdc7efb6b4.png)

Oddly enough, if I type the whole thing out correctly (without IntelliSense) and then go back over an item and press `CTRL + SPACE`, if will show me the IntelliSense for that section!
![image](https://cloud.githubusercontent.com/assets/5606334/19830918/f0f69b7e-9dc3-11e6-9ca2-c328e8c31570.png)

**Comment by NTaylorMullen** [comment] 2016-10-29 20:38
This is fixed in the next VS tooling release 😄. 

Duplicate of https://github.com/aspnet/Razor/issues/792

**Closed by NTaylorMullen** 2016-10-29 20:38 UTC
Labels: duplicate
