### ISSUE TITLE
Partial parsing modifies pre-existing SyntaxTree

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#624] opened 2015-11-30 18:56 UTC
Tooling found that after partial parsing the background parser will modify returned SyntaxTrees. This is troublesome in VisualStudio due to threading races resulting in inconsistent editing experiences occasionally.

**Comment by rynowak** [comment] 2017-12-18 16:06
Dupe of #1793 which is being worked on now.

**Closed by rynowak** 2017-12-18 16:06 UTC
