### ISSUE TITLE
visual studio messes up indentation

### ISSUE THREAD

**Issue by Spongman** [aspnet/Razor#2107] opened 2018-02-23 20:48 UTC
vs 15.5.7

````
@helper Foo(Func<object, HelperResult> p1, Func<object, HelperResult> p2)
{
}

<div>
	@Foo(
		@<text>foo</text>,
		@<text>bar</text>
	)
</div>
````

indenting this twice results in:

````

@helper Foo(Func<object, HelperResult> p1, Func<object, HelperResult> p2)
	{
}

<div>
	@Foo(
				@<text>foo</text>,
								@<text>bar</text>
											)
</div>

````

and it gets worse each time you indent.

this is a _regression_ since 15.4. while that version formatted incorrectly, at least it didn't compound the error.

we use a lot of helpers like this in our code and right now i'm telling our devs to disable razor formatting.

**Comment by Spongman** [comment] 2018-02-23 20:56
here's another one. wtf?

````
@MyHelper(
	@<text>
		@using (Bar())
					{
			<div></div>
					}
		/**/
		/**/
		/**/
		/**/
		/**/
		/**/
	</text>
)
````

**Comment by Spongman** [comment] 2018-02-23 20:59
even the simplest quoted html sends the closing brace off to infinity:

````
@MyHelper(
	@<div></div>
												)
````

**Comment by ajaybhargavb** [comment] 2018-02-24 01:06
@Spongman thanks for reporting this. I just verified it and can confirm this is indeed a regression. We already have a similar issue in our backlog. 
@NTaylorMullen since you already investigated https://github.com/aspnet/Razor/issues/1076, do you think this is a dup of it?

**Comment by NTaylorMullen** [comment] 2018-02-24 01:21
ya this is a dup

**Comment by Spongman** [comment] 2018-02-28 00:10
is there a plan to have a working indentation implementation for razor any time soon. it's been horribly broken since 2011. this seems it is the primary language for developing web UI in asp.net. there have been countless reports of its brokenness in various forums (connect, SO, uservoice, MS support forums, blogs, github) going on 7 years now and still we have to put up with a sub-par implementation for thi sessential technology.

if you can't be bothered to fix it, could you at least open-source it so we can?

**Comment by mkArtakMSFT** [comment] 2018-02-28 18:07
Thanks everyone for your input. We heard you, and are going to finally fix this. While I'm closing this in favor of the duplicate item (https://github.com/aspnet/Razor/issues/1076), I've moved that out from Backlog so we can address it in the upcoming release.

**Closed by mkArtakMSFT** 2018-02-28 18:07 UTC
