### ISSUE TITLE
Self-closing tag helper won't render content unless you call 'SuppressOutput()'

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#424] opened 2015-06-19 05:24 UTC
Suppose I have a tag helper that simply appends static output to its tag:

```
    public class Simplest : TagHelper
    {
        public override Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
            //output.SuppressOutput();
            output.Content.Append("Super simple!");

            return Task.FromResult(0);
        }
    }
```

And in Razor I have:

```
<simplest></simplest>
```

That works fine and renders:

```
<simplest>Super simple!</simplest>
```

But if I change my Razor to:

```
<simplest />
```

It doesn't render the appended contents:

```
<simplest />
```

It's not hard to imagine why this is the case: the tag is now self-closing, and so of course it can't have contents.

This is however somewhat weird. If you think of how the HTML DOM works, a self-closing tag that has inner content or tags added to it will "expand" into an open/close tag.

Perhaps we should do the same in Razor.

**Comment by Eilon** [comment] 2015-06-19 05:38
BTW if I call `SuppressOutput()` then it does work because there's no self-closing tag to "fight" against.

**Comment by dougbu** [comment] 2015-06-19 05:45
@Eilon you can also set `output.SelfClosing = false;`.

IIRC we chose not to change `SelfClosing` in the MVC tag helpers because we kept hitting strange corner cases where the behaviour would just confuse. Would likely also end up contradicting the HTML 5 spec to for example support non-self closing `<input>` elements. /cc @DamianEdwards

**Comment by davidfowl** [comment] 2015-06-19 08:40
Shouldn't it throw if it's selfclosing and you AppendChildContent?

**Comment by Eilon** [comment] 2015-06-19 18:19
@davidfowl yeah that's what I'm thinking. If it's not going to work, let me know. Or just make it work (though I could understand that might be problematic).

**Comment by NTaylorMullen** [comment] 2015-06-19 19:23
@Eilon @davidfowl There's a lot of simple cases like this that we could do which we decided not to for the sake of keeping `TagHelperOutput` as simple as possible. For instance, the opposite could be said that if you change `SelfClosing` to `true` to nuke all the content that's within the `TagHelper` (set the various content properties to `null`). 

Ultimately, I feel like if we were to do one special case such as this we'd probably want to do more for consistency. If this is the approach we want to take we should sit down to see what magic behaviors make sense to add to not confuse users via too much magic.

**Comment by Eilon** [comment] 2015-06-19 19:35
It's not magical to warn the developer/user that they are doing something that can't possibly work.

**Comment by NTaylorMullen** [comment] 2015-06-19 19:43
I wasn't commenting on the "warn the developer" solution, just the "do it" solution. If anything, warning the developer would be my preferred fix. 

As for throwing if you append content when self-closing: that'd require developers to check self-closing whenever they append content (they don't know if another `TagHelper` ran before them). A better solution may be to log a warning (don't think it's worth throwing) after all `TagHelper`s have run but before they've been written out.

**Comment by Eilon** [comment] 2015-06-19 21:01
Ah, got you about magical.

I'm not sure that logging makes sense here. No one will look at that. Especially because it'll likely be at the Debug/Verbose level. This is something that simply can't work. If it's a problem with some combination of "bad" tag helpers then as a user I'd want to know my code is getting ignored and I should report that to the author of the tag vendor.

**Comment by DamianEdwards** [comment] 2015-06-19 21:05
If multiple tag helpers are running, then the current state isn't reliable for determining error conditions like this. My tag helper may never set self-closing to true, but the one before me might, and now I throw. I don't think that's a great design. I think in this case it's right to give up a little determinism for flexibility given the nature of the composition model.

**Comment by Eilon** [comment] 2015-06-19 21:19
Flexibility == my app doesn't work sometimes? I much prefer to fail fast, even if it's not my fault.

**Comment by davidfowl** [comment] 2015-06-20 01:54
How would you ever figure this out? Isn't there a difference between what was parsed and what was changed programmatically? Sorta like what we have with attributes?

It seems like this will never work. Do we have more situations like this where the actions of a previous tag helper make actions invalid on a child tag helper by design?

**Comment by NTaylorMullen** [comment] 2015-06-20 16:43
@davidfowl We would have to add a verification stage in-between running and rendering of a tag targeted by `TagHelper`s that verified the final outputs at runtime.

As for more situations on a previous `TagHelper` running making the next invalid: Yes, there's several situations that can lead to anomalies depending on how a `TagHelper` was written. That being said though, it is possible to write `TagHelper`s very defensively to protect against previous `TagHelper`s running that result in invalid states.

**Comment by danroth27** [comment] 2015-06-22 20:27
We decided that we don't want to throw - we want to allow multiple tag helpers to run and fix up state as needed. Instead we will log any interesting tag helper state transitions before rendering.

**Comment by danroth27** [comment] 2015-06-24 21:47
https://github.com/aspnet/Razor/issues/433

**Closed by danroth27** 2015-06-24 21:47 UTC
Labels: 1 - Ready, needs design, TagHelper
