### ISSUE TITLE
asp-append-version="true" is ignored when src property is altered in custom Image Tag Helper

### ISSUE THREAD

**Issue by ajoylabroo** [aspnet/Razor#504] opened 2015-08-29 04:37 UTC
If there is a custom Image Tag Helper that manipulates the src of the image tag like this:

Example: 

```csharp

    [TargetElement("img")]
    public class ImageTagHelper : TagHelper
    {
        [HtmlAttributeName("src")]
        public string Source { get; set; }
        private readonly IConfiguration _config;
        public ImageTagHelper(IConfiguration config)
        {
            _config = config;
        }
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            if (string.IsNullOrEmpty(Source)) return;
            output.Attributes["src"] = string.Format("{0}{1}", _config["Data:DefaultConnection:BlobsEndpoint"], Source);
        }
    }
```
and this is the originating html code
```html
<img src="images/Logo.png" alt="Logo" asp-append-version="true"/>
```
The above incorrectly generates the following html without the ?v=xxxxxxxx....

```html
<img alt="Logo" src="http://127.0.0.1:10000/devstoreaccount1/images/Logo.png">
```
Is there a way to still call the base classes Process method to pick up generation of randomized querystring?

I am using Version 1.0.0-beta6

**Comment by dougbu** [comment] 2015-08-29 06:01
This may be a dupe of aspnet/Mvc#2902. That has been fixed but in the Beta 8 milestone.

One potential workaround in the meantime would be to give your tag helper a high `Order` (placing it after the MVC tag helper) and use `output.Attributes["src"]` on the right hand side of the equation (instead of `Source`).

**Comment by ajoylabroo** [comment] 2015-08-30 03:35
Thanks for promptly responding @dougbu. Its great that it has been fixed in Beta 8. Your workaround did make sense in theory but didn't work. 

Here is my _ViewImports.cshtml file

```cshtml
@using CheapClothingStore
@using CheapClothingStore.Models
@using Microsoft.AspNet.Identity
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@addTagHelper "*, CheapClothingStore"
```

Here is my ImageTagHelper.cs file

```csharp
namespace CheapClothingStore.Modules.TagHelpers
{
    [TargetElement("img")]
    public class ImageTagHelper : TagHelper
    {
        [HtmlAttributeName("src")]
        public string Source { get; set; }

        private readonly IConfiguration _config;

        public ImageTagHelper(IConfiguration config)
        {
            _config = config;
        }
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            if(output.Attributes["src"] != null)
                output.Attributes["src"].Value = string.Format("{0}{1}", _config["Data:DefaultConnection:BlobsEndpoint"], output.Attributes["src"].Value);
        }
    }
}
```

_Layout.cshtml has an img tag like this:
```cshtml
<img src="images/Logo.png" alt="CheapClothing Store Logo" asp-append-version="true"/>
```

Yet the HTML output is still generated as:

```html
<img alt="CheapClothing Store Logo" src="http://127.0.0.1:10000/devstoreaccount1/images/Logo.png">
```

Any thoughts?

**Comment by dougbu** [comment] 2015-08-30 04:38
OK @ajoylabroo thanks for trying that out. Few new questions:
- What OS are you running this on?
- Does the `wwwroot/images/Logo.png` file exist?
  - May be worth confirming the exact case even if running on Windows.
- Does the http://127.0.0.1:10000/devstoreaccount1/images/Logo.png image display correctly in your app?

**Comment by ajoylabroo** [comment] 2015-08-30 04:49
* OS: Windows 7 [Virtual]
* wwwroot/images/Logo.png file does not exist. Got rid of entire images folder. All the images are being served from within the blob container.
* I have confirmed that http://127.0.0.1:10000/devstoreaccount1/images/Logo.png does display the image correctly.

Thanks for looking into this.

**Comment by dougbu** [comment] 2015-08-30 04:52
The in-box `ImageTagHelper` will only append a file hash if it can find the file. So the "`wwwroot/images/Logo.png` file does not exist" point is likely the root cause of the problem here.

**Comment by ajoylabroo** [comment] 2015-08-30 05:04
Got it. That explains it. Is there a plan to calculate the dynamic version number for a non local Image URL in future?

**Comment by dougbu** [comment] 2015-08-30 05:16
> a plan to calculate the dynamic version number

Sounds a bit like the conversation in aspnet/Mvc#2865. The current SHA256 hashes are all we have planned. What specific alternative are you suggesting?

> still able to find the image from url

Perhaps but that would be rather inefficient. Why have you chosen to make the (local) image file inaccessible to the MVC application?

**Comment by ajoylabroo** [comment] 2015-08-30 05:48
After reading the discussion happening over in [aspnet/Mvc#2865](https://github.com/aspnet/Mvc/issues/2865), I can see the reason for having the files in local folder is required. 

In my scenario, if I have a site that has multiple pages with photos for each product and one of the photo changes, I not only need the updated photo to reside within the relative path `wwwroot/images` folder (both on local disk and Azure Web Apps local disk as well) but also within the blob so that `asp-append-version` can correctly calculate hash based on the images content and blob container will be used to serve the file.

I can understand calculating SHA256 on the fly would be inefficient and might result in delayed loading of an image, but having duplicate content on Azure doesn't feel like a polished solution. I can't think of a solution either.

**Closed** 2015-09-02 22:04 UTC
