### ISSUE TITLE
Referencing different versions of Razor.Design causes builds to fail

### ISSUE THREAD

**Issue by danjohnso** [aspnet/Razor#2553] opened 2018-08-23 14:43 UTC
We are on TFS 2018 and after updating our .NET Core SDK to 2.1.401 and updating the relevant packages in our solution, the build server is unable to build our web project.  Error is identical to this issue in the blazor project (https://github.com/aspnet/Blazor/issues/1298), but we are not using blazor.  Worst part is it is intermittent.  I will try changing setting or clearing nuget caches or repairing the sdk and it might work for one build, but then any subsequent build with no code or environment changes will fail.  Running the dotnet build command manually from cmd as the agent user will usually succeed and not run into this issue.  

```
C:\Users\tfsagent\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error MSB4062: The "Microsoft.AspNetCore.Razor.Tasks.RazorTagHelper" task could not be loaded from the assembly C:\Users\tfsagent\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\..\..\\tasks\netstandard2.0\Microsoft.AspNetCore.Razor.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\agent\_work\6\s\TES\TES.Web\TES.Web.csproj]
Build FAILED.
C:\Users\tfsagent\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error MSB4062: The "Microsoft.AspNetCore.Razor.Tasks.RazorTagHelper" task could not be loaded from the assembly C:\Users\tfsagent\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\..\..\\tasks\netstandard2.0\Microsoft.AspNetCore.Razor.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\agent\_work\6\s\TES\TES.Web\TES.Web.csproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:04.46
Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1
```

**Comment by mkArtakMSFT** [comment] 2018-08-23 17:29
Thanks for contacting us, @danjohnso.
In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by danjohnso** [comment] 2018-08-23 17:40
I'm not sure how I can provide a repo of a TFS build...I can't reproduce in
visual studio.  I have a verbose log from the dotnet build call

**Comment by pranavkm** [comment] 2018-08-23 17:55
From another thread

> The root cause likely has to do with mixing versions of the Razor tasks - which ship in Microsoft.AspNetCore.Razor.Design. Since the Razor tasks don't ship in the SDK they can be configured per-project, which can result an msbuild process trying to load conflicting versions. The workaround that users can do is to make sure they are using the same version of the Razor tasks **everywhere** OR shut down the msbuild processes in between builds.

Yet another workaround might be to disable the RazorBuildServer on your CI. Try setting `UseRazorBuildServer = false` in your CI configuration.

**Comment by rynowak** [comment] 2018-08-23 17:57
I'm not sure that shutting down the build server will help this is inside the MSBuild process, he'd have to turn off msbuild node reuse instead.

**Comment by danjohnso** [comment] 2018-08-23 18:25
I am not using msbuild directly if that makes a difference, the task calls dotnet.exe build

**Comment by danjohnso** [comment] 2018-08-23 18:36
@pranavkm interesting.  So there are 2 web projects with a reference to _Microsoft.AspNetCore.Mvc_ in the solution and one class library that references _Microsoft.AspNetCore.Mvc.Core_.  One web project targets .NET framework (_Microsoft.AspNetCore.Mvc_ package) and has no problems, the one targeting netcoreapp (_Microsoft.AspNetCore.Mvc_ via _Microsoft.AspNetCore.App_) is failing.  If I add explicit references to all 3 projects for _Microsoft.AspNetCore.Razor.Design_, it looks like the build will consistently succeed.

**Comment by pranavkm** [comment] 2018-08-23 18:42
Glad that you have a solution. @mkArtakMSFT we can use this issue to track figuring out a solution for this.

**Comment by stanuku** [comment] 2018-09-20 22:19
@pranavkm  We are on 2.1.3 with the same issues. I'm not sure the leading patch would fix this intermittent issue with TFS Build.

**Comment by fabiano** [comment] 2018-10-10 16:21
I was having the same error on our build server.

This server had two SDKs installed (2.1.401 and 2.1.403) and removing the v2.1.401 solved for us.

**Comment by TrieBr** [comment] 2018-10-12 16:32
@pranavkm I'm on 2.2-preview2 and I'm still experiencing the problem. My builds were working on 2.2-preview1 and I installed/upgraded to 2.2-preview2 today and now I receive that error. I've tried uninstalling the 2.2-preview1 SDK as fabiano mentioned, but it didn't work. I also have the 2.1 SDK installed, but I need to keep that installed for other projects I'm working on that arent ready to upgrade to 2.2

Any ideas?

**Comment by pranavkm** [comment] 2018-10-12 17:43
@TrieBr could you share more details about your project setup?

**Comment by TrieBr** [comment] 2018-10-14 15:17
@pranavkm It started working for me again, I’m unable to reproduce the issue. I think uninstalling 2.2-preview1 fixed the issue

**Comment by pranavkm** [comment] 2018-10-15 16:41
@rynowak something to try out with the 2.2 release verification - verify if the Tasks assembly fix works if you have 2.1 and 2.2 installed SxS. Closing this - we can use a release verification bug to fix this if there's an actual issue here.

**Comment by csharpfritz** [comment] 2018-10-19 16:09
This is a SIGNIFICANT issue -- GitHub is pushing folks with AspNetCore.App v2.1.0 - 2.1.3 to v2.1.4 and this issue is breaking builds with no clear resolution.

**Comment by jag43** [comment] 2018-10-24 14:29
I am getting this error when running the VSTS test task as part of a build pipeline.
```
C:\Users\VssAdministrator\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error MSB4062: The "Microsoft.AspNetCore.Razor.Tasks.RazorTagHelper" task could not be loaded from the assembly C:\Users\VssAdministrator\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\..\..\\tasks\netstandard2.0\Microsoft.AspNetCore.Razor.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\a\1\s\WebApps\WebApps.TeleM\WebApps.TeleM.csproj]
```
I'm not sure if that's because of how our project is set up or if I've misunderstood something.
`AspNetCore.Mvc` is referenced from 3 places:
- WebHelper project (via a nuget package), 
- Razor Class Library project (this already references our WebHelper project, but the explicit reference is needed for the Razor Class Library to function properly) and
- Our WebApp project references the Razor Class Library and `AspNetCore.App`

I think I have tried everything suggested here in this thread but I'm still getting the error.

> - Remove the version from the Microsoft.AspNetCore.App package reference

I removed the version from all our web app projects.
> - Add an explicit reference to the latest version of the Microsoft.AspNetCore.Razor.Design package to make sure you're getting the latest Razor MSBuild tasks.

I added this reference to all our WebApp projects and all our unit test projects, is that right?
> - Update your .NET Core SDK on your dev machine

The issue doesn't occur on our dev machines, but on the VSTS build agent. It looks like the most recent version installed on the agent is `2.1.402` (the agent is provided by VSTS)
> - For CI environments we also suggest passing the /nodeReuse:false flag

I have added this to the VSTS test, so the full command is now `dotnet test --logger:trx --configuration $(BuildConfiguration) /nodeReuse:false`

Is there anything I've missed or is there another problem here?

**Comment by mkArtakMSFT** [comment] 2018-10-24 21:42
Closing per @danroth27's comment above.
@jag43, please reopen a new issue for your specific problem.

**Closed by mkArtakMSFT** 2018-10-24 21:42 UTC
Labels: 3 - Done, PRI: 0 - Critical, bug

**Comment by IgorKravcov** [comment] 2018-10-30 11:41
Hi all, 

We seem to experience a similar issue. When trying to build the project in VS we get

_Assembly location for Razor SDK Tasks was not specified. The most likely cause is an older incompatible version of Microsoft.NET.Sdk.Razor, or Microsoft.NET.Sdk.Web used by this project. Please target a newer version of the .NET Core SDK._

We are using VS 2017, latest patch - 15.8.8 and microsoft.aspnetcore.razor.design is 2.2.0-preview3-35497. 

Tried this on vanilla .Net Core 2.1 web app and got the same issue. The only two versions of SDKs installed are  2.1.202 and 2.1.403

Just wondering if anyone else had this issue or know why this might be happening.
