### ISSUE TITLE
Tag helpers generating invalid markup. 

### ISSUE THREAD

**Issue by byteful** [aspnet/Razor#678] opened 2016-01-26 01:20 UTC
Consider the following:

      <link asp-fallback-href="~/vendor/lightbox2/css/lightbox.min.css"
      asp-fallback-test-class="lightbox"
      asp-fallback-test-property="position"
      asp-fallback-test-value="absolute"
      href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css"
      rel="stylesheet" />

The following meta tag is generated by asp:

      <meta name="x-stylesheet-fallback-test" class="lightbox" />

If I try and validate this using the HTML5 validator I receive the following error:

Validator.nu (Public): Element “meta” is missing one or more of the following attributes: “content”, “property”.

**Comment by NTaylorMullen** [comment] 2016-01-26 01:23
Duplicate of https://github.com/aspnet/Mvc/issues/3449. This is fixed in RC2.

**Closed by NTaylorMullen** 2016-01-26 01:23 UTC
Labels: duplicate
