### ISSUE TITLE
RazorPages with filenames that include a hyphen cause the tooling to break

### ISSUE THREAD

**Issue by Svek** [aspnet/Razor#1729] opened 2017-10-20 17:51 UTC
When using RazorPages￼ with filenames that include a hyphen, it causes Visual Studio's tooling to show a red squiggly line on valid code.

For example, my RazorPage called `Contact-Us.cshtml` (with the hyphen) will error:
`"The name '_____' does not exist in the current context"`

![no](https://user-images.githubusercontent.com/25241292/31834850-a302f6ac-b5f9-11e7-996e-ff137ccc242e.jpg)

Whereas, my page `ContactUs.cshtml` (without the hyphen) will be fine.

![yes](https://user-images.githubusercontent.com/25241292/31834853-a528743e-b5f9-11e7-88cb-f0581c633d28.jpg)

**Comment by NTaylorMullen** [comment] 2017-10-20 18:57
This should be fixed in the Visual Studio 15.5 release. Duplicate of https://github.com/aspnet/Mvc/issues/6296

**Closed by NTaylorMullen** 2017-10-20 18:57 UTC
Labels: duplicate
